---
title: "Trabajo Práctico Final  \nBiometría II - 2021"
author: "Matías Alemán, Milagros Azcueta, Manuel Fiz, Emilia Haberfeld, Diego Kafer, Ilan Shalom"
date: "21/10/2021"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#################################### SCRIPT ####################################

# Borrar objetos de la memoria
rm(list = ls()) 

################################################################################
####################### CARGA DE LIBRERIAS Y DATOS: ############################
################################################################################

library(readxl)    # datos de excel
library(reshape2)  # melt
library(pastecs)   # tapply
library(ggplot2)   # gráficos
library(ggeffects) # ggpredict (todavía no lo usamos)
library(dplyr)
library(geepack)   # modelado con geeglm
library(MuMIn)     # model.sel
library(glmmTMB)   # modelado con glmmTMB
library(car)       # Anova
library(emmeans)   # comparaciones
library(DHARMa)

setwd("C:/Users/hecto/Desktop/Ilán/Biome II/TP FINAL/TP-FINAL-BIOME")
datos <- read_excel("datos.xlsx")
str(datos)
datos$SEMANA         <- as.factor(datos$SEMANA)
datos$ID             <- as.factor(datos$ID)
datos$ANT            <- as.factor(datos$ANT)
datos$PROB           <- as.factor(datos$PROB)
datos$TRATAMIENTO    <- as.factor(datos$TRATAMIENTO)
str(datos)
# Colmena no la vamos a incluir en el analisis porque esta explicada por Semana.

################################################################################
############################### DESCRIPTIVA ####################################
################################################################################

################## ENTRENAMIENTO:
# PASAMOS DATOS ENTRENAMIENTO A LONG:
wide_entr <- datos[,c(1,2,3,4,5,6,7,8,9)]
long_entr <- melt(wide_entr,
                id.vars = c("SEMANA", "ID", "ANT", "PROB", "TRATAMIENTO"),
                variable.name = "tiempo_entr",
                value.name = "rta")

# PROBABILIDAD DE EXITO SEGUN TRATAMIENTO Y TIEMPO:
prob_exito_entr <- round(tapply(long_entr$rta,list(long_entr$TRATAMIENTO,long_entr$tiempo_entr),mean),2)
prob_exito_entr

# Creamos un data frame en formato long con estos valores:
prob_exito_entr_long <- as.data.frame.table(prob_exito_entr)
colnames(prob_exito_entr_long) <- c("TRATAMIENTO","nro_ensayo","proporcion_exitos")

# Reordenamos los levels para la leyenda del grafico:
prob_exito_entr_long$TRATAMIENTO <- factor(prob_exito_entr_long$TRATAMIENTO, levels = c("contraste_pos","constante_alto", "constante_bajo","contraste_neg"))

# Graficamente:
gp_entr <- ggplot(prob_exito_entr_long, aes(x=nro_ensayo, y=proporcion_exitos, colour=TRATAMIENTO, group=TRATAMIENTO)) +
  geom_line(linetype=2) +
  geom_point(size=2,shape=c(15,16,16,15,15,16,16,15,15,16,16,15,15,16,16,15)) + 
  #shape puntos
  labs(x="Numero de ensayo",y="Proporcion de PER",title="Curva de aprendizaje") +
  ylim(0,1) + theme_classic() +
  scale_colour_manual(labels = c("Contraste positivo","Constante alto",
                                 "Constante bajo","Contraste negativo"),
                      values=c("#00b050","#70ad47","#ed7c31","#ff0000")) +
  labs(col="Tratamiento") +
  guides(color = guide_legend(override.aes=list(shape=c(15,15,16,16)))) #leyenda
gp_entr

################## TESTEO:
# PASAMOS DATOS TEST A LONG:
wide_testeo <- datos[,c(1,2,3,4,5,10,11,12)]
long_testeo <- melt(wide_testeo,
                  id.vars = c("SEMANA", "ID", "ANT", "PROB", "TRATAMIENTO"),
                  variable.name = "tiempo_testeo",
                  value.name = "rta")

# PROBABILIDAD DE EXITO SEGUN TRATAMIENTO Y TIEMPO EN TESTEO:
prob_exito_testeo <- round(tapply(long_testeo$rta,list(long_testeo$TRATAMIENTO,long_testeo$tiempo_testeo), mean),2)
prob_exito_testeo

# Creamos un data frame en formato long con estos valores:
prob_exito_testeo_long <- as.data.frame.table(prob_exito_testeo)
colnames(prob_exito_testeo_long) <- c("TRATAMIENTO","tiempo_testeo","proporcion_exitos")

# Cambiamos los nombres del tiempo de testeo:
prob_exito_testeo_long$tiempo_testeo <- with(prob_exito_testeo_long, factor(tiempo_testeo,levels = c("3hs","24hs","48hs"),labels = c("3","24","48")))

# Reordenamos los levels para la leyenda del grafico:
prob_exito_testeo_long$TRATAMIENTO <- factor(prob_exito_testeo_long$TRATAMIENTO, levels = c("contraste_pos","constante_alto", "constante_bajo","contraste_neg"))

# Graficamente:
gp_testeo <- ggplot(prob_exito_testeo_long,aes(x=tiempo_testeo, y=proporcion_exitos, colour=TRATAMIENTO,group=TRATAMIENTO)) +
  geom_line(linetype=2) +
  geom_point(size=2,shape=c(15,16,16,15,15,16,16,15,15,16,16,15)) + #shape puntos
  labs(x="Tiempo de evaluacion (hs)",y="Proporcion de PER",
       title="Descriptiva evaluacion") +
  ylim(0,1) + theme_classic() +
  scale_colour_manual(labels = c("Contraste positivo","Constante alto",
                                 "Constante bajo","Contraste negativo"),
                      values=c("#00b050","#70ad47","#ed7c31","#ff0000")) +
  guides(color = guide_legend(override.aes=list(shape=c(15,15,16,16)))) + #leyenda
  labs(col="Tratamiento")
gp_testeo

################## EXPLORAMOS SEMANA COMO COVARIABLE:

prob_exito_semana <- round(tapply(long_testeo$rta,list(long_testeo$SEMANA,long_testeo$tiempo_testeo), mean),2)
prob_exito_semana
# Creamos un data frame en formato long con estos valores:
prob_exito_semana_long <- as.data.frame.table(prob_exito_semana)
colnames(prob_exito_semana_long) <- c("SEMANA","tiempo_testeo","proporcion_exitos")
# Cambiamos los nombres del tiempo de testeo:
prob_exito_semana_long$tiempo_testeo <- with(prob_exito_semana_long, factor(tiempo_testeo,levels = c("3hs","24hs","48hs"),labels = c("3","24","48")))

# Graficamente:
gp_semana <- ggplot(prob_exito_semana_long, aes(x=tiempo_testeo, y=proporcion_exitos, colour=SEMANA,group=SEMANA)) +
  geom_line(linetype=2) +
  geom_point(size=2) +
  labs(x="Tiempo de evaluacion (hs)",y="Proporcion de PER",title="Proporcion de PER en cada semana",col="Semana") +
  ylim(0,1) + theme_classic()
gp_semana

################################################################################
############################### MODELADO #######################################
################################################################################

################## PRIMERA PROPUESTA: MODELO MARGINAL (GEEGLM)
# Para geeglm, las filas del data frame tienen que estar ordenadas por paciente y por tiempo:
long_testeo <- arrange(long_testeo,ID)

# Notacion de matrices de covarianza en geeglm:
# Estructura simple: independence
# Simetria compuesta: exchangeable
# AR1: ar1
# Desestructurada: unstructured

### Interaccion tratamiento*tiempo
m5 <- geeglm(formula=rta~TRATAMIENTO*tiempo_testeo+SEMANA,family=binomial,data=long_testeo,id=ID,
             corstr="independence")
anova(m5)
m6 <- geeglm(formula=rta~TRATAMIENTO*tiempo_testeo+SEMANA,family=binomial,data=long_testeo,id=ID,
             corstr="exchangeable")
anova(m6)
m7 <- geeglm(formula=rta~TRATAMIENTO*tiempo_testeo+SEMANA,family=binomial,data=long_testeo,id=ID,
             corstr="ar1")
anova(m7)
m8 <- geeglm(formula=rta~TRATAMIENTO*tiempo_testeo+SEMANA,family=binomial,data=long_testeo,id=ID,
             corstr="unstructured")
anova(m8)

## SELECCION DE MODELOS (en geeglm rankeamos por QIC):
model.sel(m5,m6,m7,m8, rank = QIC)

# Estructura simple: la sacamos porque no estariamos declarando dependencia de datos entre tiempos para una misma abeja.
# Simetria compuesta: decimos que para cada abeja hay una misma correlacion entre tiempos.
# AR1: la sacamos porque a pesar de tener la misma cantidad de parámetros que la de simetria compuesta, tiene un peor ajuste porque nuestros tiempos no son equidistantes como asume AR1, entonces el QIC es mayor.
# Desestructurada: la sacamos porque estima mas parametros, por eso el QIC da un poco mas alto.

################## SEGUNDA PROPUESTA: MODELO CONDICIONAL (GLMMTMB)

# Como elegimos simetria compuesta, probamos un modelo condicional:

# Semana como aleatoria:
m9 <- glmmTMB(rta ~ TRATAMIENTO*tiempo_testeo +  (1|SEMANA) + (1|ID), data=long_testeo, family="binomial")

# Semana como fija:
m10 <- glmmTMB(rta ~ TRATAMIENTO*tiempo_testeo + SEMANA + (1|ID), data=long_testeo, family="binomial")

################################################################################
########################### EVALUACIÓN DE SUPUESTOS ############################
################################################################################

# Supuestos m9:
## Parte fija:
sim_m9 <- simulateResiduals(m9, n=1000)
plot(sim_m9)

# Supuestos para variable aleatoria Semana:
Bi_semana <- unlist(ranef(m9))
Bi_semana <- Bi_semana[1:7]
# QQPlot con estos residuos:
car::qqPlot(Bi_semana)
# Prueba de shapiro:
shapiro.test(Bi_semana)

# Supuestos para variable aleatoria ID:
Bi_ID <- unlist(ranef(m9))
Bi_ID <- Bi_ID[8:139]
# QQPlot con estos residuos:
# QQPlot con estos residuos:
car::qqPlot(Bi_ID)
# Prueba de shapiro:
shapiro.test(Bi_ID)

# Supuestos m10:
## Parte fija:
sim_m10 <- simulateResiduals(m9, n=1000)
plot(sim_m10)

# Supuestos para variable aleatoria ID:
Bi_ID_10 <- unlist(ranef(m10))
car::qqPlot(Bi_ID_10)
shapiro.test(Bi_ID_10)

# PARA M10 (SEMANA FIJA) NO HAY EVIDENCIAS PARA RECHAZAR CUMPLIMIENTO DE SUPUESTOS DE LA PARTE FIJA NI ALEATORIA (ID).
# PARA M9 NO SE CUMPLE LA NORMALIDAD DE LA VARIABLE ALEATORIA ID.

AIC(m9,m10)
# Elegimos usar m10 porque mejora el AIC y se cumplen los supuestos.
    
################################################################################
########################## ESTIMACIÓN E INFERENCIA #############################
################################################################################

Anova(m10)
summary(m10)

################################################################################
############################### COMPARACIONES ##################################
################################################################################

# Seteamos el emmeans:
options(emmeans= list(emmeans = list(infer = c(TRUE, TRUE)),
                      contrast = list(infer = c(TRUE, TRUE))))


##### CONTRASTES ORTOGONALES (TENEMOS COMPARACIONES A PRIORI)

ortogonales<-emmeans(m10,~TRATAMIENTO*tiempo_testeo,type="response",
                contr=list("3hs_alto_pos"=c(1,0,0,-1,0,0,0,0,0,0,0,0), 
                     "3hs_bajo_neg"=c(0,1,-1,0,0,0,0,0,0,0,0,0), 
                     "24hs_alto_pos"=c(0,0,0,0,1,0,0,-1,0,0,0,0), 
                     "24hs_bajo_neg"=c(0,0,0,0,0,1,-1,0,0,0,0,0), 
                     "48hs_alto_pos"=c(0,0,0,0,0,0,0,0,1,0,0,-1), 
                     "48hs_bajo_neg"=c(0,0,0,0,0,0,0,0,0,1,-1,0)))

ortogonales 

################################################################################
############################### GRÁFICO FINAL ##################################
################################################################################

res_modelo <- as.data.frame(ortogonales$emmeans)

# Cambiamos los nombres del tiempo de testeo:
res_modelo$tiempo_testeo <- with(res_modelo, factor(tiempo_testeo,
                                                    levels = c("3hs","24hs","48hs"),
                                                    labels = c("3","24","48")))
# Reordenamos los levels para la leyenda del grafico:
res_modelo$TRATAMIENTO <- factor(res_modelo$TRATAMIENTO,
                                 levels = c("contraste_pos","constante_alto",
                                            "constante_bajo","contraste_neg"))

# Graficamos:
gp_final <- ggplot(res_modelo,aes(x=tiempo_testeo,y=prob,group=TRATAMIENTO,color=TRATAMIENTO)) +  
  labs(x="Tiempo de evaluacion (hs)",y="Proporcion de PER",title="Estimaciones del modelo") +
  geom_errorbar(aes(ymin=(prob-res_modelo$SE),ymax=(prob+res_modelo$SE)),
                width=.2,color="lightgrey") +
  geom_line(linetype=2) +
  geom_point(size=2,shape=c(15,16,16,15,15,16,16,15,15,16,16,15)) + #shape puntos
  labs(col="Tratamiento") +
  theme_classic() +
  ylim(0,1) +
  scale_colour_manual(labels = c("Contraste positivo","Constante alto",
                                 "Constante bajo","Contraste negativo"),
                      values=c("#00b050","#70ad47","#ed7c31","#ff0000")) + #leyenda
  guides(color = guide_legend(override.aes=list(shape=c(15,15,16,16)))) +  #leyenda
  annotate(geom="text",x="24",y=1,label="*",color="#00b050",size=10) + #significancia
  annotate(geom="text",x="48",y=1,label="*",color="#ff0000",size=10)   #significancia
  
gp_final

########## RESUMEN DE GRAFICOS ########## 
# Descriptiva entrenamiento:
gp_entr
# Descriptiva testeo:
gp_testeo
# Semana como covariable:
gp_semana
# Grafico final con significancias:
gp_final

```

